
from __future__ import annotations

import json
import sys
from pathlib import Path

SRC = Path(__file__).resolve().parents[1] / "src"
sys.path.insert(0, str(SRC))

from change_gate.data import seed  # noqa: E402


def q(v: str) -> str:
    return "'" + v.replace("'", "''") + "'"


def jb(v) -> str:
    return q(json.dumps(v))


def pg_array(items) -> str:
    inner = ",".join('"' + str(i) + '"' for i in items)
    return q("{" + inner + "}")


def gen() -> str:
    lines: list[str] = [
        "-- AUTO-GENERATED by db/generate_seed_sql.py — do not edit by hand.",
        "-- Mirrors change_gate.data.seed exactly.",
        "BEGIN;",
    ]

    for tid, ctx in seed.TENANTS.items():
        name = {"acme": "Acme Corp", "globex": "Globex Inc"}.get(tid, tid)
        lines.append(
            f"INSERT INTO tenants(tenant_id, name) VALUES ({q(tid)}, {q(name)}) "
            "ON CONFLICT DO NOTHING;"
        )

        p = ctx.policy
        lines.append(
            "INSERT INTO policies(tenant_id, env_criticality, env_authority, factor_weights, "
            "band_low_max, band_medium_max, recency_lookback_days, magnitude_full_delta, "
            "blast_radius_saturation, auto_approve_max_band) VALUES (\n"
            f"  {q(tid)},\n"
            f"  {jb({k.value: v for k, v in p.env_criticality.items()})},\n"
            f"  {jb({k.value: sorted(r.value for r in v) for k, v in p.env_authority.items()})},\n"
            f"  {jb(dict(p.factor_weights))},\n"
            f"  {p.band_low_max}, {p.band_medium_max}, {p.recency_lookback_days}, "
            f"{p.magnitude_full_delta}, {p.blast_radius_saturation}, "
            f"{q(p.auto_approve_max_band.value)}\n) ON CONFLICT DO NOTHING;"
        )

        for sid, svc in ctx.graph.services.items():
            lines.append(
                f"INSERT INTO services(tenant_id, id, name, traffic_fraction) VALUES "
                f"({q(tid)}, {q(sid)}, {q(svc.name)}, {svc.traffic_fraction}) "
                "ON CONFLICT DO NOTHING;"
            )
        for sid, deps in ctx.graph.depends_on.items():
            for dep in sorted(deps):
                lines.append(
                    "INSERT INTO service_dependencies(tenant_id, service_id, depends_on_id) "
                    f"VALUES ({q(tid)}, {q(sid)}, {q(dep)}) ON CONFLICT DO NOTHING;"
                )
        for (key, env), cv in ctx.config.items():
            lines.append(
                "INSERT INTO config_state(tenant_id, key, environment, kind, value) VALUES "
                f"({q(tid)}, {q(key)}, {q(env.value)}, {q(cv.kind.value)}, {jb(cv.value)}) "
                "ON CONFLICT DO NOTHING;"
            )
        for fw in ctx.freeze_windows:
            lines.append(
                "INSERT INTO freeze_windows(tenant_id, id, name, start_ts, end_ts, "
                "environments, reason) VALUES "
                f"({q(tid)}, {q(fw.id)}, {q(fw.name)}, {q(fw.start.isoformat())}, "
                f"{q(fw.end.isoformat())}, {pg_array(sorted(e.value for e in fw.environments))}, "
                f"{q(fw.reason)}) ON CONFLICT DO NOTHING;"
            )
        for inc in ctx.incident_history:
            lines.append(
                "INSERT INTO incident_history(tenant_id, service_id, at_ts, severity, resolved) "
                f"VALUES ({q(tid)}, {q(inc.service_id)}, {q(inc.at.isoformat())}, "
                f"{q(inc.severity)}, {str(inc.resolved).lower()});"
            )
        for ch in ctx.change_history:
            lines.append(
                "INSERT INTO change_history(tenant_id, service_id, key, environment, at_ts, "
                f"decision) VALUES ({q(tid)}, {q(ch.service_id)}, {q(ch.key)}, "
                f"{q(ch.environment.value)}, {q(ch.at.isoformat())}, {q(ch.decision.value)});"
            )

    for s in seed.SCENARIOS:
        r = s.request
        lines.append(
            "INSERT INTO change_requests(tenant_id, id, requester_id, requester_role, "
            "service_id, key, kind, environment, current_value, proposed_value, "
            "window_start, window_end) VALUES (\n"
            f"  {q(r.tenant_id)}, {q(r.id)}, {q(r.requester.id)}, {q(r.requester.role.value)},\n"
            f"  {q(r.service_id)}, {q(r.key)}, {q(r.kind.value)}, {q(r.environment.value)},\n"
            f"  {jb(r.current_value)}, {jb(r.proposed_value)}, "
            f"{q(r.window_start.isoformat())}, {q(r.window_end.isoformat())}\n"
            ") ON CONFLICT DO NOTHING;"
        )

    lines.append("COMMIT;")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    out = Path(__file__).resolve().parent / "03_seed.sql"
    out.write_text(gen(), encoding="utf-8")
    print(f"wrote {out}")
